version: 2.1

commands:
  checkout_and_install:
    description: "Checkout the repo and install dependencies."
    steps:
      - checkout

      - restore_cache:
          keys:
            - doctor-v2-{{ arch }}-{{ checksum "package-lock.json" }}
            - doctor-v2-{{ arch }}-
            - doctor-v2-

      - run:
          name: Install Dependencies
          command: |
            echo "Node version: $(node --version)"
            echo "NPM version:  $(npm --version)"
            npm ci

      - save_cache:
          key: doctor-v2-{{ arch }}-{{ checksum "package-lock.json" }}
          paths:
            - ~/.npm

jobs:
  Test:
    parameters:
      node-version:
        type: string
    docker:
      - image: "cimg/node:<< parameters.node-version >>"
    steps:
      - checkout_and_install
      - run:
          name: Tests
          command: |
            npm test

  Lint:
    docker:
      - image: "cimg/node:18.12"
    steps:
      - checkout_and_install
      - run:
          name: Lint
          command: |
            npm run lint

workflows:
  build:
    jobs:
      - Test:
          matrix:
            parameters:
              node-version: ["12.22", "14", "16", "18", "20", "22"]
      - Lint
